### ISSUE TITLE
KeyError: 96

### ISSUE THREAD

**Issue by kungfooman** [athre0z/wasm#2]
Hi, just did a simple test:

```
int add(int a, int b) {
	return a + b;
}
```

```emcc testwasm.c -o test.wasm -s WASM=1 -s SIDE_MODULE=1```

Command `wasmdump --disas test.wasm` fails with:

```
emscripten@euve254883:~$ wasmdump --disas test.wasm
- [ ModuleHeader
  | magic = 0x6d736100
  | version = 0x1
- [ Section
  | id = 0
  | payload_len = 12
  | name_len = 6
  | name = "dylink"
  | payload = [0x80, 0x80, 0xc0, 0x2, 0x0, 0x1, 0x9c, 0x80, 0x80, 0x80, 0x0, 0x6]
  | overhang = []
Traceback (most recent call last):
  File "/home/emscripten/.local/bin/wasmdump", line 11, in <module>
    load_entry_point('wasm==1.1', 'console_scripts', 'wasmdump')()
  File "/home/emscripten/.local/lib/python2.7/site-packages/wasm/__main__.py", line 34, in dump
    for cur_sec, cur_sec_data in mod_iter:
  File "/home/emscripten/.local/lib/python2.7/site-packages/wasm/decode.py", line 45, in decode_module
    sec_len, sec_data, _ = sec.from_raw(None, module_wnd)
  File "/home/emscripten/.local/lib/python2.7/site-packages/wasm/types.py", line 302, in from_raw
    data_len, val, data_type = cur_field.from_raw(data, raw[offs:])
  File "/home/emscripten/.local/lib/python2.7/site-packages/wasm/types.py", line 188, in from_raw
    return self.choice_field_map[choice].from_raw(ctx, raw)
KeyError: 96
```

Version `emcc -v`:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.18
clang version 4.0.0  (emscripten 1.37.18 : 1.37.18)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: E:\emsdk-1.35.0-portable-64bit\clang\e1.37.18_64bit
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by athre0z** [comment]
Mhhh yeah, I can reproduce that. Will take a look, thanks for reporting!

**Comment by pventuzelo** [comment]
This error is still there, do you find out the root cause?

**Comment by athre0z** [comment]
There was an issue with the payload length calculation for custom sections (id=0). Could you check if my commit on `develop` resolves the issue with your binary as well?

**Comment by pventuzelo** [comment]
yes, it worked. thanks
